import os
import glob
import re
import yaml
from lxml import etree
from src.config import INPUT_DIR, DBT_OUTPUT_DIR

class ContextParser:
    """
    Parses Talend Context files (.item) to generate a dynamic dbt variables configuration.
    Decouples logic from environment specific values (DEV/TEST/PROD).
    """
    def __init__(self):
        self.context_dir = os.path.join(INPUT_DIR, "context")
        self.output_file = os.path.join(DBT_OUTPUT_DIR, "dbt_project_vars.yml")
        self.global_vars = {}

    def parse(self):
        print(f"[INFO] Scanning for Context files...")
        
        # 1. Try standard context directory
        files = glob.glob(os.path.join(self.context_dir, "**", "*.item"), recursive=True)
        
        # 2. Fallback: Scan entire project if standard folder is empty
        if not files:
            print(f"[WARN] No context files found in {self.context_dir}. Scanning entire project...")
            files = glob.glob(os.path.join(INPUT_DIR, "**", "*.item"), recursive=True)

        valid_files = 0
        for f in files:
            if self._process_context_item(f):
                valid_files += 1

        self._write_dbt_vars()
        print(f"[SUCCESS] Context Mapped: {len(self.global_vars)} variables found across {valid_files} files.")

    def _process_context_item(self, filepath):
        try:
            # FIX: Windows Encoding Safety & XML Recovery
            parser = etree.XMLParser(recover=True, encoding='utf-8')
            tree = etree.parse(filepath, parser=parser)
            
            # Find context parameters (Generic XPath)
            params = tree.xpath("//contextParameter")
            
            if not params:
                return False # Not a context file

            # Regex to find sensitive keys
            sensitive_pattern = re.compile(r"(pass|secret|key|token|pwd)", re.IGNORECASE)

            for param in params:
                name = param.get("name")
                value = param.get("value")

                if not name:
                    continue

                # GENERIC FEATURE: Security Masking
                # Map sensitive vars to dbt env_vars, others to literal values
                if sensitive_pattern.search(name):
                    dbt_val = f"{{{{ env_var('TALEND_{name.upper()}') }}}}"
                else:
                    dbt_val = value or ""

                self.global_vars[name] = dbt_val
            
            return True

        except Exception:
            # Silently skip files that aren't valid XML or Contexts
            return False

    def _write_dbt_vars(self):
        """Writes the consolidated variables to a YAML file for dbt."""
        if not self.global_vars:
            return

        os.makedirs(os.path.dirname(self.output_file), exist_ok=True)
        
        output_data = {"vars": self.global_vars}

        # FIX: Force UTF-8 encoding
        with open(self.output_file, 'w', encoding='utf-8') as f:
            f.write("# AUTOMATICALLY GENERATED BY TALEND-TO-DBT-SOURAV-AGENT\n")
            f.write("# Mapped from Talend Context Groups\n\n")
            yaml.dump(output_data, f, default_flow_style=False, sort_keys=True)